@echo off
echo Starting Backend...
start powershell -NoExit -Command "cd backend; .\my_venv\Scripts\python -m uvicorn main:app --reload --port 8001"
echo Starting Frontend...
start powershell -NoExit -Command "cd frontend; npm run dev"
echo Both servers starting in new windows...
pause
