# pdf_writer.py

from fpdf import FPDF
import os
from datetime import datetime

COMPANY_EMAIL = "partha@infinitetechai.com"
COMPANY_PHONE = "+91 98847 77171"

class PDF(FPDF):
    def header(self):
        self.set_fill_color(0, 51, 102) # Dark blue
        self.set_text_color(255, 255, 255) # White text
        self.set_font("DejaVu", "B", 16)
        self.cell(0, 15, "DM Thermoformer | Sales Inquiry Summary", ln=True, align="C", fill=True)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")

    def section_title(self, title):
        self.set_font("DejaVu", "B", 12)
        self.set_fill_color(230, 230, 230) # Light grey
        self.set_text_color(0, 0, 0) # Black text
        self.cell(0, 8, title, ln=True, fill=True, align="L")
        self.ln(4)

    def add_detail_row(self, label, value):
        self.set_font("DejaVu", "B", 11)
        self.cell(60, 8, label, 0, 0, 'L')
        self.set_font("DejaVu", "", 11)
        self.multi_cell(0, 8, str(value), 0, 'L')
        self.ln(1)

def setup_fonts(pdf_instance):
    font_path = os.path.join(os.path.dirname(__file__), "fonts") 
    if not os.path.exists(os.path.join(font_path, "DejaVuSans.ttf")):
        print("WARNING: DejaVu fonts not found. Using Arial.")
        pdf_instance.add_font("Arial", "", "Arial.ttf", uni=True) 
        pdf_instance.add_font("Arial", "B", "Arialbd.ttf", uni=True)
        pdf_instance.add_font("Arial", "I", "Arial.ttf", uni=True) 
        pdf_instance.set_font("Arial", "B", 12)
    else:
        pdf_instance.add_font("DejaVu", "", os.path.join(font_path, "DejaVuSans.ttf"), uni=True)
        pdf_instance.add_font("DejaVu", "B", os.path.join(font_path, "DejaVuSans-Bold.ttf"), uni=True)
        pdf_instance.add_font("DejaVu", "I", os.path.join(font_path, "DejaVuSans-Oblique.ttf"), uni=True)

def create_sales_pdf(user_details, output_path):
    print(f"[*] Starting create_sales_pdf for {output_path}")
    pdf = PDF()
    setup_fonts(pdf)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)

    # --- Header Information ---
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, f"Ref: DM-INQ-{datetime.now().strftime('%Y%m%d')}", ln=0, align='L')
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%B %d, %Y')}", ln=True, align='R')
    pdf.ln(5)

    # --- Client Details ---
    pdf.section_title("Client Contact Information")
    pdf.add_detail_row("Contact Person:", user_details.get('contact_person', 'N/A'))
    pdf.add_detail_row("Company Name:", user_details.get('company', 'N/A'))
    pdf.add_detail_row("Company Address:", user_details.get('company_address', 'N/A'))
    pdf.add_detail_row("Email Address:", user_details.get('email', 'N/A'))
    pdf.add_detail_row("Phone Number:", user_details.get('phone', 'N/A'))
    pdf.ln(5)

    # --- Project Requirements ---
    pdf.section_title("Technical Inquiry Details")
    pdf.add_detail_row("Division:", user_details.get('division', 'N/A'))
    pdf.add_detail_row("Project Type:", user_details.get('product_type', 'N/A'))
    pdf.add_detail_row("Plastic Properties:", user_details.get('properties', 'N/A'))
    pdf.add_detail_row("Preferred Material:", user_details.get('material', 'N/A'))
    pdf.add_detail_row("Material Thickness:", user_details.get('thickness', 'N/A'))
    pdf.add_detail_row("Drawing Available:", user_details.get('drawing_available', 'N/A'))
    pdf.add_detail_row("Dimensions:", user_details.get('dimensions', 'N/A'))
    pdf.add_detail_row("Quantity Required:", user_details.get('quantity', 'N/A'))
    pdf.add_detail_row("Timeline/Urgency:", user_details.get('timeline', 'N/A'))
    pdf.add_detail_row("Delivery Location:", user_details.get('delivery_location', 'N/A'))
    pdf.add_detail_row("Sample Required:", user_details.get('sample_needed', 'N/A'))
    pdf.add_detail_row("Forecast Demand:", user_details.get('forecast', 'N/A'))
    pdf.ln(10)

    # --- Footer Note (Internal) ---
    pdf.set_font("DejaVu", "I", 10)
    pdf.multi_cell(0, 6, "Report generated by AI Assistant. Priority: Standard. Please follow up within 24 hours.")

    try:
        pdf.output(output_path)
        print(f"Sales PDF saved successfully at: {output_path}")
    except Exception as e:
        print(f"Error while saving Sales PDF: {e}")